### ISSUE TITLE
Encoded state

### ISSUE THREAD

**Issue by TDominiak** [JulesBelveze/time-series-autoencoder#14]
Hi,

As I understand well you create y_hist in order to perform training using teacher forcing by providing the true target value to the  Decoder. As an argument to the forward Decoder function, you only pass y_hist. I cannot understand why you do not pass also the Encoded Vector as the final hidden state produced from the encoder part of the model.

Thanks

**Comment by JulesBelveze** [comment]
Hey @TDominiak thanks for actually pointing that out, that does not seem right to me either. Tbh I haven't tried the model without attention!
Would you like to open a PR that fixes the case or a regular decoder?? 😄 (shouldn't be too much work)

**Comment by TDominiak** [comment]
Yes, sure. after i finish analyzing the solution with attention i will take care of this bug.

**Comment by JulesBelveze** [comment]
Hey @TDominiak just checking out if you need some help?
