### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by qq583** [JulesBelveze/time-series-autoencoder#15]
ValueError: Index Date_Time invalid

**Comment by JulesBelveze** [comment]
Hey @qq583 can you please provide more information on how to reproduce that bug?

**Comment by qq583** [comment]
When I run run_forecasting.py ,it prompt “Traceback (most recent call last):
  File "D:/untitled2/forecasting/run_forecasting.py", line 54, in <module>
    df = pd.read_csv("data/AirQualityUCI.csv", index_col=config["index_col"])”，and “ValueError: Index Date_Time invalid”.
please tell me how to solve this problem. thank you !!!!

**Comment by JulesBelveze** [comment]
@qq583 if I go to the root folder and run:
```
python3 -m examples.forecasting.run_forecasting --do-train=True
```
Can you try to do that?

**Comment by qq583** [comment]
sorry i can‘t . The trouble is "df = pd.read_csv("data/AirQualityUCI.csv", index_col=config["index_col"])" .
and "ValueError: Index Date_Time invalid"

**Comment by JulesBelveze** [comment]
Have you downloaded the dataset?

**Comment by qq583** [comment]
Yes,but i don't know the title of the data. my data title is "



<meta name="Generator" content="Microsoft Excel">

<style>

</style>




Date | Time | CO(GT) | PT08.S1(CO) | NMHC(GT) | C6H6(GT) | PT08.S2(NMHC) | NOx(GT) | PT08.S3(NOx) | NO2(GT) | PT08.S4(NO2) | PT08.S5(O3) | T | RH | AH
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --







",is it true?

**Comment by JulesBelveze** [comment]
My bad the `.csv` wasn't the right one. Try again with the data from [here](https://gist.github.com/JulesBelveze/e9997b9b0b68101029b461baf698bd72)

**Comment by qq583** [comment]
sorry , i can't download this data,could you put this data into this package ?
Thank you very much!!!!!!

**Comment by JulesBelveze** [comment]
There's a `download zip` button on the top right.

**Comment by qq583** [comment]
Thank you , my bro!!!
