### ISSUE TITLE
Not working for many of the tickers

### ISSUE THREAD

**Issue by Rajmehta123** [JulesBelveze/time-series-autoencoder#23]
The model worked fine for Netflix ticker but when I run for some other ticker, the model doesn't seem to learn. Or it learns with large errors.

Can you try to predict for the following attached dataset? Also, please attach the config as well.

https://drive.google.com/file/d/18lJk5JouTRomHV2wli99uUL3qWG1N8Vy/view?usp=sharing

![image](https://user-images.githubusercontent.com/22636443/132290125-c40eddf4-7f7e-4afc-b101-084ea0fa2a27.png)

My configs:
```
label_col=["close"],  # name of target column
index_col="date",

output_size=1,  # for forecasting

num_epochs=200,
batch_size=64,
lr=3e-4,
reg1=True,
reg2=False,
reg_factor1=1e-4,
reg_factor2=1e-4,
seq_len=20,  # previous timestamps to use
prediction_window=1,  # number of timestamps to forecast
hidden_size_encoder=128,
hidden_size_decoder=128,
input_att=True,
temporal_att=True,
denoising=True,
directions=1,

max_grad_norm=0.1,
gradient_accumulation_steps=1,
logging_steps=100,
lrs_step_size=5000,

```

**Comment by JulesBelveze** [comment]
Hey @Rajmehta123 my first attempts were not really successful, I'm getting similar results than you.
Will dig a bit deeper.
