### ISSUE TITLE
“feature, y_hist, target = batch” in the "train.py" raised error "ValueError: not enough values to unpack (expected 3, got 2)"

### ISSUE THREAD

**Issue by AmberLay** [JulesBelveze/time-series-autoencoder#3]
“feature, y_hist, target = batch” in the "train.py" raised error "ValueError: not enough values to unpack (expected 3, got 2)",because "batch" only has two values,so what does "y_hist" mean? Sorry I just know a little about Attention ,I just want to run first.

**Comment by JulesBelveze** [comment]
Hey @AmberLay , thanks for opening the issue. There's indeed a problem, the iterator only returns 2 arguments. I'll fix this.

`y_hist` is basically `target` but shifted one timestamp to the left. You need this to predict the first timestamp of each time window since you use the actual `y[t-1]` to predict `y[t]`. Does that make sense?

**Comment by JulesBelveze** [comment]
@AmberLay I've done a fix on the branch `fix/dataset` but I have no way of testing it atm.. would you mind testing it on your dataset and let me know if that works? I'll then merge the fix.

**Comment by AmberLay** [comment]
I see, thank you for your reply.But when I tested on my dataset after your fixed the bug, another bug happend. I tried to fix, but problems seem too many, such as `AttnEncoder` object has no attribute 'directions', 'Indexerror' in the slice loop 'y_history[:, t]' but 'y_history' has the shape (X,1), 'Object of type device is not JSON serializable' in the ‘dump(config, f)’ function, ... . I should spend more time on your  code and the paper, but I have no enouge free time now, maybe  I will fix these in the future. If you can fix further, thank you so much.

**Comment by JulesBelveze** [comment]
Alright, I'll try to spend some time on it. I'm closing this issue though. Feel free to open new ones if you encounter any other bugs.
