### ISSUE TITLE
I need to work with Google Colab? any get started exa;ple please?

### ISSUE THREAD

**Issue by Med-Rokaimi** [JulesBelveze/time-series-autoencoder#38]

**Comment by JulesBelveze** [comment]
Hey @Med-Rokaimi!
Thanks for your interest 🤓 They are a couple of ready-to-use examples in the `examples/` folder

**Comment by Med-Rokaimi** [comment]
Thank you for reply.
Yes I started with them. Just as I'm working with colab, it seems the env didn't work fine with me and the required packages as well.
