### ISSUE TITLE
Memory overflow due to unclosed plt

### ISSUE THREAD

**Issue by deneal123** [JulesBelveze/time-series-autoencoder#48]
<img width="465" alt="image" src="https://github.com/user-attachments/assets/58d9b2ef-450a-4203-80f1-753386e11d8e">

If evaluation is carried out during training, memory will go beyond the boundaries
I watched in real time how the reconstruction graph was changing and got a memory overflow :)

**Comment by JulesBelveze** [comment]
Hey @deneal123 thanks for pointing that out! Feel free to open a short PR if you have the fix 🙏🏼 
I'll have a look at it ASAP otherwise 👍🏼
